'use client';

import './globals.css'
import type { Metadata } from 'next'
import { SessionProvider } from 'next-auth/react';
import { Inter } from 'next/font/google'
import NavBar from './NavBar';
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  session,
  children,
}: {
  children: React.ReactNode
}) {
  return (

    <html lang="en">
      <body className={inter.className}>
    <SessionProvider session={session}>
          <Head> {/* Add the Head component */}
            <link rel="icon" href="/favicon.ico" /> {/* Add the favicon link */}
          </Head>
       <NavBar />
      {children}
    </SessionProvider>
      </body>
    </html>
  )
}

